### ISSUE TITLE
Sort list with script

### ISSUE THREAD

**Issue by nunomaduro** [php-youtubers/directory#50]
Would be interesting a "sort.php" script to sort this list by number of subscribers. Someone up to hack on that? Maybe also display the number of subscribers in the process?

**Comment by hrsa** [comment]
That's a good idea! I'll try it out this evening, unless someone does it earlier 👍

**Comment by devfaysal** [comment]
I wrote this a while ago https://github.com/devfaysal/YouTube_Channel_Statistics
I will try soon.

**Comment by Joeri-Abbo** [comment]
https://github.com/php-youtubers/directory/pull/62
Maybe Python is a better fit and can be use in combination with github actions to automate it futher?
It is pretty fast because of async

**Comment by hrsa** [comment]
https://github.com/php-youtubers/directory/pull/62
https://github.com/php-youtubers/directory/pull/61
https://github.com/php-youtubers/directory/pull/57

3 solutions available! 👍

**Comment by nunomaduro** [comment]
Done.
