### ISSUE TITLE
API Key in source code

### ISSUE THREAD

**Issue by RVxLab** [php-youtubers/directory#64]
This issue is more to provide visibility that the API key is currently in the source code. As @hrsa mentioned in #61, it’s a free key for ease of testing but it doesn’t mean it should be overlooked. 

While not a big deal for now, better to have an open issue to remind everyone that this should probably be done.

**Comment by nunomaduro** [comment]
@hrsa can you remove it?

**Comment by RVxLab** [comment]
If hsra has no opportunity to remove it I can have a look tomorrow (AEST time). 

@nunomaduro Are you intending to run this in a GH Action at all? If so I would vote adding an environment variable and/or a CLI longopt.

**Comment by hrsa** [comment]
API key removed in https://github.com/php-youtubers/directory/commit/1f8a9087892330c0df2b3234fea6a89c57e36dc8 !

**Comment by RVxLab** [comment]
Legend! I’ll close this issue now then.
